name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: AhsanAyaz/angular-deploy-gh-pages-actions
      with:
        deploy_branch: gh-pages
        build_configuration: staging # The build environment for the app. please look configurations in your angular.json
        base_href: /frecciadidiana/   # make sure this corresponds to https://<your_username>.github.io/<base_href>/
